.yarnrc.yml
tsconfig.json
webpack.dev.js
webpack.prod.js

chore(webpack): Fix eslint rule

---

.eslintrc.json

import order 순서 명시적으로 지정.
라이브러리 -> 상대경로(부모/형제) -> index

feat(eslint): Change import/order rules

---

.vscode/extensions.json
.vscode/settings.json
package.json

resolve #32 
stylelint auto fix
- vscode extensions, setting 추가
- script 추가 -> @ooooorobo husky 오류 나면 `yarn stylelint:fix` 명령어 입력해주심 됩니다.
한 번 해보시면 좋을 것 같습니다~

[Setting] stylelint auto fix

---

webpack.dev.js
webpack.prod.js

chore(webpack): Change webpack import order

---

src/features/dailyBook/components/Container.tsx
src/style/dailyBook.scss

feat(dailyBook): Add background gradient

---

src/features/detail/components/CloseButton.tsx
src/features/detail/components/Cover.tsx

fix(detail): fix svg path

---

src/features/dailyBook/Container.tsx
src/features/dailyBook/components/CoverImage.tsx
src/style/dailyBook.scss

feat(dailybook): Set image cover style fit

---

src/features/gallery/Container.tsx
src/features/gallery/components/MasonryLayout/index.tsx
src/features/gallery/constants/index.ts
src/features/gallery/helpers/index.ts

Gallery 인터랙션 수정
이미지 개수에 따라 움직이는 범위가 달라짐(5, 10, 20, 30, 50개 실험 완료)
https://user-images.githubusercontent.com/62797441/222772553-bd365273-b4dd-4603-b076-00356a57746c.mp4
https://user-images.githubusercontent.com/62797441/222772997-9ef5047a-3f2b-4c74-8c83-f97d85549a5d.mp4
없습니다.

[Feat] Gallery 인터랙션 수정

---

src/features/about/Container.tsx
src/features/about/constants.ts
src/features/about/helpers.ts
src/features/about/hooks/useInteraction.tsx
src/style/about.scss

PR의 개요를 적어주세요.
image 올려서 인터렉션 보고 아직 작업중입니다

Feat/about 이미지 인터렉션 적용 확인

---

src/features/dailyBook/constants.ts
src/features/detail/Container.tsx
src/features/detail/components/Description.tsx
src/features/detail/types.ts
src/style/detail.scss

날짜마다 디테일 사진 데이터 수정해줌
사진 하나면 이미지 슬라이드 안씀

fix(detail): 디테일 데이터 수정

---

src/features/dailyBook/Container.tsx
src/features/dailyBook/components/CoverImage.tsx
src/style/dailyBook.scss

feat(dailybook): Add image interaction

---

src/features/about/Container.tsx
src/features/about/constants.ts
src/features/about/helpers.ts
src/features/about/hooks/useInteraction.tsx
src/style/about.scss

PR의 개요를 적어주세요.
about main interaction

feat(about): apply main interaction

---

src/features/dailyBook/Container.tsx
src/features/dailyBook/components/Container.tsx
src/features/dailyBook/constants.ts
src/style/dailyBook.scss

feat(dailybook): Add title interaction

---

src/features/about/Container.tsx
src/features/about/hooks/useInteraction.tsx
src/style/about.scss

PR의 개요를 적어주세요.
end...!
scrollTo가 안돼요

feat(about): apply end page interaction

---

src/App.tsx

fix: remove text

---

src/style/detail.scss

PR의 개요를 적어주세요.
이거 타이틀 줄바꿈 안되게 함 ..

fix: change font size

---

src/style/detail.scss

- 이미지 모달 max height 지정
- 커버이미지 넘크면 마지막 섹션까지 커버이미지 보이는거 수정

fix(detail): fix detail style

---

src/style/about.scss

PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
as-is
Uploading 화면 기록 2023-03-04 오후 1.36.31.mov…
https://user-images.githubusercontent.com/40057032/222875955-e348a354-4384-46d3-b270-ef61acd6f832.mov
to-be
https://user-images.githubusercontent.com/40057032/222875913-68928702-881c-41c1-a153-c0640632e828.mov

fix(about): use absolute

---

src/style/about.scss

fix(about): enable scroll on hover fixed elements

---

src/features/dailyBook/Container.tsx
src/features/landing/components/ScrollToEnter.tsx
src/style/about.scss

- dailybook에서 스크롤 텍스트 변경
- 어바웃 이미지 박스에 pointer event 제거

fix: fix dailybook scroll text
